### ISSUE TITLE
Doesn't always work

### ISSUE THREAD

**Issue by pjebs** [CAFxX/gcnotifier#2]
```go
import "runtime/debug"
go func() {
		debug.SetGCPercent(-1)
		go func() {
			ticker := time.NewTicker(30 * time.Second)
			for {
				select {
				case <-ticker.C:
					runtime.GC()
				}
			}
		}()

		gcn := gcnotifier.New()
		for range gcn.AfterGC() {
			fmt.Println("Garbage Collected") // Not always detected
		}
	}()
```

It doesn't always work even when I have a finalizer for an object that informs me that GC has actually run.

**Comment by CAFxX** [comment]
@pjebs the reason for this is because `gcn` is dead as soon as you enter the `for range`.

This is the reason why the example in the readme includes `gcn.Close()`, that is missing in your example. If you add the `gcn.Close()` after the loop, or you otherwise keep `gcn` alive, you'll see it always works (or at least, I can't make it not work; if you have a minimal runnable example I can take another look).

Sorry for the late reply, I missed the notification.
